### ISSUE TITLE
Why honcho in particular? 

### ISSUE THREAD

**Issue by GildedHonour** [tonlabs/tonos-se#11]
1) Why is honcho in **particular** used here?

2) What's the neccessity? Why not run all of them without honcho, as ordinary processes? Is it specific to the fact that it's all done in Docker?

**Comment by DezzK** [comment]
1. Honcho allows orchestrating several processes in parallel using a single and simple configuration file (profile).
2. It's not specific to Docker. Of course, you don't have to use honcho and similar tools, but, in that case, you have to orchestrate all processes manually. For example, if one of the processes failed to start, you have to stop all other processes. Honcho can simplify this as much, as possible.
