### ISSUE TITLE
 What's nginx for here?

### ISSUE THREAD

**Issue by GildedHonour** [tonlabs/tonos-se#12]
> What's nginx for here?
> 
> It is used for routing requests for Node SE or Q-Server, according to the path. You can inspect its configuration for deeper investigation: https://github.com/tonlabs/tonos-se/blob/master/docker/nginx.conf.d
> 

What route them for?

**Comment by DezzK** [comment]
> What route them for?
Because different queries must be processed by different processes. For example, /graphql queries can be served only by Q-Server, not by the node. If you are planning to make your own installation, you may not change this behavior because it can harm all applications that use TON SDK.
