### ISSUE TITLE
[Windows] Subscribe for transactions with addresses (ABIv1) test failed

### ISSUE THREAD

**Issue by ch1seL** [tonlabs/tonos-se#13]
Steps to reproduce:

- Build and Run Node SE from https://github.com/tonlabs/tonos-se/tree/master/ton-node-se
- Run tests from https://github.com/tonlabs/ton-client-js#run-tests

Result:
```
PS>$env:USE_NODE_SE="true";$env:TON_NETWORK_ADDRESS="http://localhost:8080";node run
1.11.0
✓ Test versions compatibility (1 / 0)
✓ crypto (2 / 0)
✓ encode_message (3 / 0)
✓ net (4 / 0)
✓ Block signatures (5 / 0)
✓ All Accounts (6 / 0)
✓ Ranges (7 / 0)
✓ Wait For (8 / 0)
𐄂 Subscribe for transactions with addresses (ABIv1) (8 / 1) - [
    {
        "matcherResult": {
            "pass": false
        },
        "message": "\u001b[2mexpect(\u001b[22m\u001b[31mreceived\u001b[39m\u001b[2m).\u001b[22mtoBeGreaterThan\u001b[2m(\u001b[22m\u001b[32mexpected\u001b[39m\u001b[2m)\u001b[22m\n\nExpected: > \u001b[32m0\u001b[39m\nReceived:   \u001b[31m0\u001b[39m"
    }
]
✓ Subscribe for transactions with addresses (ABIv2) (9 / 1)
✓ Subscribe for messages (ABI v1) (10 / 1)
✓ Subscribe for messages (ABI v2) (11 / 1)
✓ Transactions with addresses (12 / 1)
✓ Check shard_hashes greater then 0 (13 / 1)
---
success: 13
failure: 1
```

PS: I've open PR with a workaround for tests https://github.com/tonlabs/ton-client-js/pull/206

**Comment by joydark** [comment]
Would you please retry test again. After `tondev se start` needs ~30 sec for node to start its services.

**Comment by nrukavkov** [comment]
> Would you please retry test again. After `tondev se start` needs ~30 sec for node to start its services.

Thank you for your answer, but a workaround wouldn’t help, I guess

**Comment by nrukavkov** [comment]
We do not use docker image. In this case we use Windows build of tonos-se

**Comment by joydark** [comment]
Accepted test changes
