### ISSUE TITLE
Build failed. aes-ctr crate is DEPRECATED

### ISSUE THREAD

**Issue by ch1seL** [tonlabs/tonos-se#49]
root@13485a15bdb7:/tonos-se/ton-node-se# cargo build --release
    Updating crates.io index
    Updating git repository `https://github.com/tonlabs/ton-labs-block.git`
    Updating git repository `https://github.com/tonlabs/ton-labs-block-json.git`
    Updating git repository `https://github.com/tonlabs/ton-labs-executor.git`
    Updating git repository `https://github.com/tonlabs/ton-labs-types.git`
    Updating git repository `https://github.com/tonlabs/ton-labs-vm.git`
    Updating git repository `https://github.com/tonlabs/ton-labs-tl.git`
    Updating git repository `https://github.com/tonlabs/ton-labs-assembler.git`
    Updating git repository `https://github.com/paritytech/rust-secp256k1`
    Updating git repository `https://github.com/tonlabs/TON-SDK.git`
    Updating git repository `https://github.com/tonlabs/lockfree.git`
error: failed to select a version for the requirement `stream-cipher = "^0.3"`
candidate versions found which didn't match: 0.99.99, 0.7.1, 0.6.0, ...
location searched: crates.io index
required by package `aes-ctr v0.3.0`
    ... which is depended on by `adnl v0.0.4 (/tonos-se/ton-node-se/adnl)`
    ... which is depended on by `ton_node_startup v0.28.4 (/tonos-se/ton-node-se/ton_node_startup)`

**Comment by ch1seL** [comment]
btw it would be nice to fix the build of previous versions

**Comment by DezzK** [comment]
The issue has been fixed. Thank you for reporting.
